table Product
	lineageTag: e9374b9a-faee-4f9e-b2e7-d9aafb9d6a91

	/// Total number of products in the Product table
	measure '# Products' = COUNTROWS('Product')
		formatString: #,##0
		displayFolder: 0. Measures
		lineageTag: 1f8f1a2a-06b6-4989-8af7-212719cf3617

	/// Full name of the product
	column Product
		dataType: string
		displayFolder: 1. Product
		lineageTag: da435585-1f9a-44bd-ba2c-34c98f298cfc
		isDefaultLabel
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column 'Product Key'
		dataType: int64
		isHidden
		isKey
		formatString: 0
		displayFolder: 3. Keys
		isAvailableInMdx: false
		lineageTag: 4184d53e-cd2d-4cbe-b8cb-04c72a750bc4
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	/// Unique alphanumeric code identifying the product
	column 'Product Code'
		dataType: string
		displayFolder: 3. Keys
		lineageTag: e9d204ad-76d8-4db9-9d1a-b9c07a4b50b2
		summarizeBy: none
		sourceColumn: Product Code

		annotation SummarizationSetBy = Automatic

	/// Company that manufactures the product
	column Manufacturer
		dataType: string
		displayFolder: 1. Product
		lineageTag: 59e45f50-f68d-44c3-becd-70ccd5a7eb7d
		summarizeBy: none
		sourceColumn: Manufacturer

		annotation SummarizationSetBy = Automatic

	/// Brand name of the product
	column Brand
		dataType: string
		displayFolder: 1. Product
		lineageTag: a71b235d-8f7e-4678-85a3-96a78d64bf87
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	/// Color of the product
	column Color
		dataType: string
		displayFolder: 2. Attributes
		lineageTag: 7054b4d0-6d93-4c96-be74-800d02d96e43
		summarizeBy: none
		sourceColumn: Color

		annotation SummarizationSetBy = Automatic

	/// Unit of measure used for the product weight (e.g., kg, lb)
	column 'Weight Unit Measure'
		dataType: string
		displayFolder: 2. Attributes
		lineageTag: 78fcf7c4-2b5d-45b0-abf9-6ee3b3aa255b
		summarizeBy: none
		sourceColumn: Weight Unit Measure

		annotation SummarizationSetBy = Automatic

	/// Weight of the product in its designated weight unit
	column Weight
		dataType: decimal
		displayFolder: 2. Attributes
		lineageTag: a6299b36-bd05-4b41-8493-e45359af237b
		summarizeBy: none
		sourceColumn: Weight

		annotation SummarizationSetBy = Automatic

	/// Standard cost to produce or purchase the product
	column 'Unit Cost'
		dataType: decimal
		displayFolder: 2. Attributes
		lineageTag: f89fa3e3-061d-4269-8cd3-aa6ce2a464d2
		summarizeBy: none
		sourceColumn: Unit Cost

		annotation SummarizationSetBy = Automatic

	/// Standard retail price of the product
	column 'Unit Price'
		dataType: decimal
		displayFolder: 2. Attributes
		lineageTag: ef300027-e4eb-4c7d-9770-ab8f6dab6b15
		summarizeBy: none
		sourceColumn: Unit Price

		annotation SummarizationSetBy = Automatic

	/// Code identifying the product subcategory
	column 'Subcategory Code'
		dataType: string
		displayFolder: 3. Keys
		lineageTag: 7cd08eb9-2cad-4263-ae88-8c5121a68b7e
		summarizeBy: none
		sourceColumn: Subcategory Code

		annotation SummarizationSetBy = Automatic

	/// Product subcategory name
	column Subcategory
		dataType: string
		displayFolder: 1. Product
		lineageTag: 0a208c62-4bdd-4873-af18-ebc286c5b3bb
		summarizeBy: none
		sourceColumn: Subcategory

		annotation SummarizationSetBy = Automatic

	/// Code identifying the product category
	column 'Category Code'
		dataType: string
		displayFolder: 3. Keys
		lineageTag: c0fc218a-5a06-4757-9172-2d303a67f3ff
		summarizeBy: none
		sourceColumn: Category Code

		annotation SummarizationSetBy = Automatic

	/// Top-level product category name
	column Category
		dataType: string
		displayFolder: 1. Product
		lineageTag: 0f4b99cc-fdb6-4f04-b7d9-bbdcf7b2c601
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	partition Product-171f48b3-e0ea-4ea3-b9a0-c8c673eb0648 = m
		mode: import
		source =
				let
					Source = Csv.Document(
						Web.Contents(HttpSource, [RelativePath = "RAW-Product.csv"]),
						[
							Delimiter = ",",
							Columns = 14,
							Encoding = 65001,
							QuoteStyle = QuoteStyle.None
						]
					),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					#"Changed Column Types" = Table.TransformColumnTypes(
						#"Promoted Headers",
						{
							{"ProductKey", Int64.Type},
							{"Product Code", type text},
							{"Product Name", type text},
							{"Manufacturer", type text},
							{"Brand", type text},
							{"Color", type text},
							{"Weight Unit Measure", type text},
							{"Weight", Currency.Type},
							{"Unit Cost", Currency.Type},
							{"Unit Price", Currency.Type},
							{"Subcategory Code", type text},
							{"Subcategory", type text},
							{"Category Code", type text},
							{"Category", type text}
						}
					),
					#"Renamed Columns" = Table.RenameColumns(#"Changed Column Types", {{"Product Name", "Product"}})
				in
					#"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

